### ISSUE TITLE
HoldoutCherrySplit.py 

### ISSUE THREAD

**Issue by aalmuarik** [MaurizioFD/recsys-challenge-2020-twitter#1]
While executing the HoldoutCherrySplit, we found this follow Error
![image](https://user-images.githubusercontent.com/18738089/94961856-2f7f2c80-04fe-11eb-8d97-eb44c6143347.png)
Any Ideas How to fix it?
Thanks

**Comment by aalmuarik** [comment]
Anyone encountered this problem?

**Comment by DragonBanana** [comment]
Hi,
This error appears when the dataset does not have the expected number of columns. Can you please check the train and validation dataset have 24 columns, and the test dataset has 20 columns.
Can you also try to list all the operations you did, so we can try to reproduce the error?

**Comment by aalmuarik** [comment]
Hello there, 
Let me take you through what I did.
So basically
 1) We downloaded the latest data sets available at RecSys2020 website and put it in the master of the repository.
 2) then we made sure all of pip installations  are correct and up to date by executing "pip install -r requirement.txt" 
 3) then we used the compress shell file to compress all of the files.
 4) Then we Split the training set into holdout_new_train.csv.gz and holdout_new_test.csv.gz. by executing
     "cp ./Utils/Data/Split/HoldoutSplit.py ."
     "python HoldoutSplit.py"
     this one went smoothly no errors were encountered.
5) Then we executed the next step "Split the resulting training set into cherry_train.csv.gz and cherry_val.csv.gz".
   by executing  
   "cp ./Utils/Data/Split/HoldoutCherrySplit.py ."
    "python HoldoutCherrySplit.py"

Here we encountered the error, the script created the train/raw/ file with raw_feature_tweet_id.pck.gz. 
but after that no files were created then we got the following image as indicated above.

I followed the exact steps indicated in your Github repo.
but still didn't manage to fix it.

I'm not sure if the latest dataset has some faulty things from the RecSys Organizers or not. 
Also please, If you have any idea where I should check the #of columns of the different data files as I was trying to traces how to check the #of columns but the project is kinda big and didn't manage to find exactly where.

**Comment by aalmuarik** [comment]
Oh!
We made sure the train and val were 24.
But test was also 24 column.
I think after the Challenge finished they made the timestamps with test data.
Does that mean a simple drop of the last four columns "Time stamps" would solve the problem?
Thanks.

**Comment by DragonBanana** [comment]
Thank you for letting us notice. In the next days, I'll push a patch in order to make the code also compatible with the new dataset.

Dropping the 4 timestamp columns will make the code compatible. You should do it for both the test datasets (the one called 'test' and the one called 'last_test').

**Comment by aalmuarik** [comment]
Thank you very much. 
I'll try to fix it myself, if i couldn't i'll wait for your push.
Hope you have a blast.
Best regards.

**Comment by aalmuarik** [comment]
Made a quick fix on the test data, by writing a new test file with 20 columns.
![image](https://user-images.githubusercontent.com/18738089/95028700-def90200-06aa-11eb-95b7-690be88dca46.png)
I'll put it on my github.
I used Dask library for reading the test file.
[Updated]
Problem still persists, I'll wait for your fix 
Thanks.

**Comment by aalmuarik** [comment]
Hi btw we fixed, the Issue the files (test,val) should all be modified to have 20 columns.
Then everything will work smoothly.
Thanks.
