### ISSUE TITLE
Tiny one line mistake

### ISSUE THREAD

**Issue by faisalst** [MaurizioFD/recsys-challenge-2020-twitter#2]
In "UserBasicFeaturesDictArray.py",  line 209, 
I think It should be:
 engager_last_test_target_feature = RawFeatureEngagerIsVerified("last_test")
instead of:
engager_last_test_target_feature = RawFeatureCreatorIsVerified("last_test")

**Comment by DragonBanana** [comment]
Hi,
Thank you for letting us notice.

I just pushed a small patch to fix this problem.
